### ISSUE TITLE
Document workaround for #281 under ARM platforms

### ISSUE THREAD

**Issue by issuemover631** [airsonic/documentation#12]
<a href="https://github.com/qlyoung"><img src="https://avatars0.githubusercontent.com/u/6827003?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [qlyoung](https://github.com/qlyoung)**
_Monday Jul 03, 2017 at 03:40 GMT_
_Originally opened as https://github.com/Libresonic/documentation/issues/12_

----

Per my comment on libresonic/libresonic#281, issues with extremely long deployment times under OpenJDK are not limited to Raspbian / *Pi platforms but in fact appear to be caused by OpenJDK under any Jessie + ARM platform. It looks like the response to that issue was to add an installation guide for Raspbian that simply noted that Oracle's JRE should be used on that platform (#10).

While helpful, since this problem appears to affect all ARM platforms (at least under Jessie), I believe the problem itself should be explicitly documented along with the appropriate workaround. Among other things this will improve google-ability; I was on the verge of giving up and resorting to the crappy adware subsonic deb because it *Just Worked :tm:*

Unless core devs object to this I'll open a pull request to this effect when I have some spare time.

**Comment by jooola** [comment]
@qlyoung If you can do this It will be awesome !

**Comment by qlyoung** [comment]
no idea what the point of this fork is but you're welcome to pull it into your trunk if you like

https://github.com/Libresonic/documentation/pull/13

**Comment by jooola** [comment]
Thanks for the PR !

Yeah, the point of this fork is pretty simple : Don't have one person ruling on the project .
Libresonic isn't a community project, so we forked to create one !

If you would like to have more infos about the forking : 
[Rebrand ticket](https://github.com/airsonic/airsonic/issues/476)
[Airsonic README (history section)](https://github.com/airsonic/airsonic#history)

Currenlty Libresonic don't have any maintainers since the 3-4 who maintained libresonic went here !

**Comment by jooola** [comment]
e348885 closed this ! Thank you !
